sudo: required

services:
  - docker

notifications:
  email:
    recipients:
      - revett@cityofzion.io
    on_success: never
    on_failure: always

script:
  - make check-version
  - make integration-tests