version: '3.4'
networks:
  host-exposed:
    driver: bridge
  inside:
    internal: true

services:
  neo-scan-api:
    container_name: neo-scan-api
    depends_on:
      - postgres
    environment:
      DB_DATABASE: neoscan_prodv
      DB_HOSTNAME: postgres
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      NEO_SEEDS: >-
        http://128.1.61.238:34002
      PORT: 4000
      REPLACE_OS_VARS: 'true'
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/4000
      timeout: 10s
    image: 'cityofzion/neoscan:latest'
    labels:
      autoheal: 'true'
    networks:
      - inside
      - host-exposed
    ports:
      - '34000:4000'
    restart: always

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: 'library/postgres:12-alpine'
    networks:
      - inside
    restart: always
